server:
  servlet:
    context-path: /order-service
  port: 8080



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: root


product:
  service:
    base:
      uri: http://localhost:8090
